services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-service
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

  adminer-service:
    image: adminer
    container_name: adminer-service
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
